print("Hello World")
fruits=["mango","banana","apple","grapes","guava"]
print(fruits)
subjects=["maths","science","socials","english","hindi"]
print(subjects)
cities=["bareilly","delhi","mumbai","bengaluru","noida"]
print(cities)
fruits.append("orange")
print(fruits)
subjects.append("sanskrit")
print(subjects)
cities.append("chennai")
print(cities)
fruits.remove("guava")
print(fruits)
subjects.remove("sanskrit")
print(subjects)
cities.remove("chennai")
print(cities)